# SPDX-License-Identifier: GPL-2.0-only
# Match the S0 Picasso single-chip configuration without global C flags.
subdir-ccflags-y += -DONE_PL_CHIP
obj-y += ASH_ATTR/ ASH_Report/ ASH_Factory/ ASH_GPIO/
obj-y += ASH_Hardware/ ASH_Algo/
